### ISSUE TITLE
Add instructions how to set up the external providers

### ISSUE THREAD

**Issue by leastprivilege** [waqaskhan540/IdentityServerExternalAuth#2]
and on the client - preferably using the IdentityModel library.

**Comment by waqaskhan540** [comment]
Thanks.. I am on it..

**Comment by waqaskhan540** [comment]
@leastprivilege  I am closing the issue.. please review the updates and feel free to share your thoughts..

**Comment by leastprivilege** [comment]
You also need some instructions what to do at Google, Facebook etc to get this up and running...

**Comment by waqaskhan540** [comment]
All the providers have got better documentation on this, I think only a link to these would suffice.

**Comment by waqaskhan540** [comment]
but can add a sample project for each of the provider

**Comment by leastprivilege** [comment]
links are fine too

**Comment by waqaskhan540** [comment]
@leastprivilege  which constructor overload of ```GrandValidationResult``` should I use if I only want to send a message and ```customResponse``` ... because for now If I use the overload ```CustomGrandValidationResult(Dictionary<string,object> customResponse)``` it sends the access token too.

**Comment by leastprivilege** [comment]
You can only send an error message or a token.

**Comment by waqaskhan540** [comment]
Thanks.
