### ISSUE TITLE
can I use this in Javascript client ?

### ISSUE THREAD

**Issue by Vikaskumargd** [waqaskhan540/IdentityServerExternalAuth#3]

**Comment by waqaskhan540** [comment]
@Vikaskumargd  Yes you can use it with Javascript client, I have pushed a sample project for google authentication using Javascript client, see the samples and let me know if you have any issues..

**Comment by waqaskhan540** [comment]
@Vikaskumargd  should I close the issue now?

**Comment by Vikaskumargd** [comment]
Yes. Thanks @waqaskhan540

**Comment by waqaskhan540** [comment]
you'r welcome
