### ISSUE TITLE
why not request for token exchange at identityserver direct ?

### ISSUE THREAD

**Issue by hyunoosung** [waqaskhan540/IdentityServerExternalAuth#9]
I see JavaScriptClient is posting google accesstoken to externalAuth/login endpoint instead directly call IdentityServer as below.

`function getIdentityServerToken() {
            var googleAccessToken = user.Zi.access_token;
            var profile = user.getBasicProfile();
            var client_url = "http://localhost:4420/ExternalAuth/Login";

            var request = {
                Email: profile.getEmail(),
                AccessToken: googleAccessToken,
                Provider: "Google"
            };

            $.post(client_url, request, function (result) {
                if (result.error) {
                    //need to show form
                    console.log(result.error)
                } else if (result.access_token) {
                    idsrv_accessToken = result.access_token;
                }
            })
        }`

and then the .net core app request token exchange using tokenClient.RequestCustomGrantAsync()

Can I request token exchange directly to IdentityServer?

**Comment by hyunoosung** [comment]
Figured out.

`function getIdentityServerToken() {
            var googleAccessToken = user.Zi.access_token;
            var profile = user.getBasicProfile();
            var client_url = "http://localhost:17640/connect/token";
                        
            var request = {
                client_id: "Test.Client",
                client_secret: "secret",
                grant_type : "external",
                scope : "Test.WebApi",
                provider : "Google",
                external_token : googleAccessToken,
                email : profile.getEmail()
            }

            $.post(client_url, request, function (result) {
                if (result.error) {
                    //need to show form
                    console.log(result.error)
                } else if (result.access_token) {
                    idsrv_accessToken = result.access_token;
                }
            })
        }`

just add client_id, secret, grant_type, scope with request params and request token to IdentityServer.

**Comment by waqaskhan540** [comment]
@hyounoo great!!
